### ISSUE TITLE
Operator is missing permissions for `Leases` resources

### ISSUE THREAD

**Issue by jneuff** [KWasm/kwasm-operator#166]
Installing your helm chart as is, results in the operator being unable to create its `Leases`, because it is missing the permissions to do so. Shouldn't this be part of the `/templates/role.yaml`? E.g.:
```
..
- apiGroups:
  - "coordination.k8s.io"
  resources:
    - leases
  verbs:
  - get
  - update
  - patch
  - create
  ```
  I am not sure which verbs it needs, definitely `create`.
