### ISSUE TITLE
 Implement rolling update strategy

### ISSUE THREAD

**Issue by voigt** [KWasm/kwasm-operator#75]
```
  # rolloutStrategy describes how a change to this shim will be applied to nodes.
  rolloutStrategy:
    type: rolling
    rolling:
      maxUpdate: 5 # could also be a percentage of nodes, like 10% of nodes.
```

https://github.com/KWasm/kwasm-operator/blob/feat-lifecycle-manager/internal/controller/shim_controller.go#L211
