### ISSUE TITLE
Add Shim Status information to `.shim.status`

### ISSUE THREAD

**Issue by voigt** [KWasm/kwasm-operator#78]
As a shim operator, I would like to see correct status information per shim in the `.shim.status` field.

Furthermore we'd like to display proper conditions, depending on the rollout state of the shim.

Possible example:

```
status:
  nodes: 3
  readyNodes: 2
  updatedNodes: 2
  conditions:
  - lastTransitionTime: "2024-01-30T22:38:57Z"
    lastUpdateTime: "2024-01-30T22:38:57Z"
    message: Shim has minimum availability.
    reason: MinimumShimsAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-01-30T22:38:54Z"
    lastUpdateTime: "2024-01-30T22:39:06Z"
    message: Job "<nodename>-<shimname>" has successfully progressed.
    reason: NewShimAvailable
    status: "True"
    type: Progressing
```

Please consider this as an idea for inspiration only. I welcome any suggestions for displaying the relevant status information!
